### ISSUE TITLE
Error: Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by bytewiz** [hustcc/jest-canvas-mock#2]
Using jest-canvas-mock still throw this error when running jest: 
`Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)`

**Comment by bytewiz** [comment]
I messed one thing up :v: seems to work

**Comment by hustcc** [comment]
😁

**Comment by icfantv** [comment]
@hustcc It looks like this is thrown (and causes Jest to fail) simply by your initial `getContext` check [here](https://github.com/hustcc/jest-canvas-mock/blob/master/src/window.js#L13).

I had to ~monkey-patch~ borrow your code and remove that line to get Jest to not fail for me.

**Comment by hustcc** [comment]
Can you show me the screenshot of throw？

And what is the version of jest and jsdom.

**Comment by bytewiz** [comment]
@hustcc I just made a typo 😄

**Comment by hustcc** [comment]
@icfantv @dariusk ping~

**Comment by dariusk** [comment]
Thanks! Turns out all I actually had to do to fix this was, well, install the canvas npm package as described in the error message!

**Comment by icfantv** [comment]
@dariusk and others:  installing canvas requires the nodeJS headers plus other native libraries so that it can be built locally.  If your CI is in an environment that does not have Internet access for security reasons and uses, say, an Artifactory server, downloading canvas and building, or even other prebuilt binaries (e.g., canvas-prebuilt) this will not work and mocking is probably the right way to go.

@hustcc sorry for the delay, let me see if i can whip something up quickly.

**Comment by icfantv** [comment]
@hustcc apologies, I misspoke earlier and updated my original comment to be more precise.  While the tests pass, JSDom complains loudly for each one.  This is a [known issue with JSDom](https://github.com/jsdom/jsdom/pull/1964) but while node-canvas is still in alpha, they're not going to fix it.

Sadly, even wrapping with a try/catch (which is a horrible solution as you shouldn't use exception handling for flow control) doesn't work.  My personal opinion is that since the entire point of this library is to actually mock the canvas element deferring to the locally installed version, if present, might not actually be the right solution.  I would argue the reason people use mocks is precisely because they don't need (or want) the full implementation of whatever is being mocked.

Here's the stacktrace:
```
$ jest --config=jest.config.json
 PASS  src/app/components/modal/ModalContainer.test.tsx
  ● Console

    console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
          at module.exports (/Users/adam.gordon/code/cban-web-client/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at HTMLCanvasElementImpl.getContext (/Users/adam.gordon/code/cban-web-client/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
          at HTMLCanvasElement.getContext (/Users/adam.gordon/code/cban-web-client/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
          at Object.<anonymous>.exports.default (/Users/adam.gordon/code/cban-web-client/node_modules/jest-canvas-mock/lib/window.js:18:39)
          at Object.<anonymous> (/Users/adam.gordon/code/cban-web-client/node_modules/jest-canvas-mock/lib/index.js:10:38)
          at Runtime._execModule (/Users/adam.gordon/code/cban-web-client/node_modules/jest-runtime/build/index.js:448:13)
          at Runtime.requireModule (/Users/adam.gordon/code/cban-web-client/node_modules/jest-runtime/build/index.js:265:14)
          at new Runtime (/Users/adam.gordon/code/cban-web-client/node_modules/jest-runtime/build/index.js:149:14)
          at /Users/adam.gordon/code/cban-web-client/node_modules/jest-runner/build/run_test.js:64:15
          at Generator.next (<anonymous>) undefined
```

**Comment by hustcc** [comment]
So catch the throw by `try ... catch` can solve the bug? https://github.com/hustcc/jest-canvas-mock/commit/0c8d5486ebeb1fecd4fc51d27e23ca5b2dfa8e32

**Comment by icfantv** [comment]
@hustcc No, the try/catch will NOT solve it.  Given the JSDom library's authors, I didn't dig into JSDom's code as to why, though it would probably only take a few minutes.

If you want to be clever, I might suggest allowing a configuration option (assuming Jest allows such a thing for setup files) to bypass a native canvas check and just use the mocked value.

**Comment by hustcc** [comment]
Code here: https://github.com/jsdom/jsdom/blob/4c7698f760fc64f20b2a0ddff450eddbdd193176/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js#L42-L45

JSDom did not implement this method `getContent`, instead by throw an error `Error: Not implemented: HTMLCanvasElement.prototype.getContext`. So try catch the error, then use mock-canvas to mock the API of canvas, I think it is effective.

The point is I can not reproduce this problem locally, and what your jest and jsdom version?

**Comment by bytewiz** [comment]
@hustcc actually I also installed [canvas prebuilt](https://www.npmjs.com/package/canvas-prebuilt) that worked for me better than installing the canvas package 👍

**Comment by icfantv** [comment]
@hustcc latest version of Jest, 22.3.0 and we do not install JSDom directly rather, Jest pulls it in (version 11.6.2 according to its package.json).  In order to reproduce and utilize your actual mock code and have the error displayed, you will need to ensure that no prebuilt version of canvass is installed (and there are several as indicated above).

As I mentioned, the tests still pass, but each test that ultimately uses canvass will log that error.

@bytewiz That works for us when running locally, but our CI environments are locked down and do not have internet access for security reasons so downloading prebuilt binaries is not allowed.

**Comment by hustcc** [comment]
@icfantv Reproduce this problem locally.

JSDom's function `notImplemented` is not throw error, it is console.error. Two way can solve it：

 - Remove the [lines](https://github.com/hustcc/jest-canvas-mock/blob/master/src/window.js#L12-L26), I will done this.
 - In setup.js of jest, mock console.error.

```js
global.window.console.error = (...a) = { console.warning(...a) };
```

**Comment by hustcc** [comment]
v1.0.1 published, used in [echarts-for-react](https://github.com/hustcc/echarts-for-react/blob/master/package.json#L104). When node version = 5, another error of jsdom occurred.

In addition, I think PR can be send to JSDom to fix this issue.

**Comment by icfantv** [comment]
@hustcc sorry, I’m confused.  I did reproduce the problem locally.  Note that it is a cosmetic error and our Jest tests do still pass.  Since we pulled your code in-house and modified it for or purposes, I’m not sure we need to do anything else.

Regarding your modification of window.console, I think that is a terrible idea.  Modification of the standard DOM is a very dangerous road to go down, even if only in the land of testing...

**Comment by hustcc** [comment]
use v1.0.1 can avoid the error.

the lastest jsdom implement the function `getContext`, but the function only print the error, and return undefined.

So when we run the ci with jest-canvas-mock@1.0.0, will execute print the error, because of the return is undefined, so we mock it successfully.

The correct way for jsdom is throw error instead of print error when the function is waiting for completed.

**Comment by yhlben** [comment]
The error repetition at this version:
```
"jest": "^23.6.0",
"jest-canvas-mock": "^1.1.0",
```

**Comment by hustcc** [comment]
any detail information？ such as screenshot, jsdom version, demo.

**Comment by yhlben** [comment]
jest: (23.6.0)
jest-canvas-mock: (1.1.0)
jsdom: (11.12.0)  is installed by jest.
[travis-ci result](https://travis-ci.org/yhlben/cdfang-spider/jobs/482384811)
[demo](https://github.com/yhlben/cdfang-spider)

![image](https://user-images.githubusercontent.com/13692434/51474145-5a246280-1db9-11e9-9ed3-4464cc8a84f3.png)

**Comment by yhlben** [comment]
Thanks. Finally I override `console.error` in my Jest setup to avoid the error. @icfantv

**Comment by hustcc** [comment]
I think can send a pr to jsdom.

**Comment by ssolders** [comment]
If you don't need to test the getContext-method explicitly and for the sake of getting a cleaner test-log you can mock the method by:

```
window.HTMLCanvasElement.prototype.getContext = () => {}
```

Example of a test case
```
describe('MyComponent should render', () => {
    it('should render', () => {
      window.HTMLCanvasElement.prototype.getContext = () => {}
      mount(MyComponent)
   })
 })
```

**Comment by jtenner** [comment]
```ts
  HTMLCanvasElement.prototype.getContext = getContext2D;
```

Indeed this is fixed in the current version.

![image](https://user-images.githubusercontent.com/3761339/52965740-8eb51b00-3373-11e9-9f60-be109f5d37d7.png)

I just added these tests and they pass in the alpha, but they will be added to the beta for clarity reasons.

**Comment by danieldanielecki** [comment]
Solution proposed by @ssolders was almost fine to avoid the following error

> Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

In my case it I had to mock this method in my .spec.ts file

`
HTMLCanvasElement.prototype.getContext = jest.fn();
`

However, in my scenario I tested [particles.js](https://vincentgarreau.com/particles.js/), having Jest as a testing framework I still had another error

> TypeError: Cannot read property 'fillRect' of undefined

With 1 line of code change was able to get rid off these 2, in essence to my Jest config setupFiles array (jest.config.js, using [Nx workspace](https://nrwl.io/nx/guide-nx-workspace/)) imported [jest-canvas-mock](https://github.com/hustcc/jest-canvas-mock) like so

`'./../../node_modules/jest-canvas-mock/lib/index.js'`

Finding this as a leaner approach, maybe for some of you guys might be useful, here is a [link](https://medium.com/@justintulk/how-to-mock-an-external-library-in-jest-140ac7b210c2) to Medium super short post about global mocks for external libraries. The author says about global mocks, but I took the part with **setupFiles** in **package.json**. As mentioned earlier, using [Nx workspace](https://nrwl.io/nx/guide-nx-workspace/)) for [Angular](https://angular.io/), for me it was to set it up in **jest.config.js**, and it works fine. In my **package.json** don't have [jsdom](https://github.com/jsdom/jsdom/), below necessary code snippets to reproduce, as well dependencies with its versions.

**package.json**


```
"dependencies": {
  ...
  "particles.js": "^2.0.0",
  ...
},
"devDependencies": {
  ...
  "jest": "^23.0.0",
  "jest-canvas-mock": "^2.0.0-alpha.3",
  "jest-preset-angular": "6.0.1"
  ...
```


**jest.config.js**


```
module.exports = {
  name: 'home-components',
  preset: '../../jest.config.js',
  coverageDirectory: '../../coverage/libs/home-components',
  setupFiles: [
    './../../node_modules/particles.js/particles.js', // Replace import * as particlesJS from 'particles.js' in the test file.
    './../../node_modules/jest-canvas-mock/lib/index.js' // Get rid off HTMLCanvasElement.prototype.getContext, and canvas errors. Now no need to mock in the test file explicitly.
  ]
};
```


Now my .spec.ts is simple as that, without throwing any error

```
import { 
  async, 
  TestBed 
} from '@angular/core/testing';
import { HomeComponentsModule } from './home-components.module';

describe('HomeComponentsModule', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [HomeComponentsModule]
    }).compileComponents();
  }));

  it('should create home components module', async(() => {
    expect(HomeComponentsModule).toBeTruthy();
  }));
});
```


Before even though the component was working totally on **ng serve** without any single error/warning. After running tests **ng test** I started to get all these errors, took 2-3 days for me to fix it, if anyone of you'd have similar issues, just try to follow the snippets, should be fine.

**Comment by chenxiaochun** [comment]
I solved this problem is:
1. Install`jest-canvas-mock`
2. Add config in jest config:`setupFiles: ['<rootDir>/jest/setup.js', 'jest-canvas-mock'],
`

**Comment by JasonLunsford** [comment]
Solution proposed by @chenxiaochun solved my issue. Thank you!

**Comment by danieldanielecki** [comment]
Looks great @chenxiaochun, that time I was solving the issue `jest-canvas-mock` was in early alpha and didn't solve my issue, glad to see now it's much easier :)

**Comment by namlq93** [comment]
> I solved this problem is:
> 
> 1. Install`jest-canvas-mock`
> 2. Add config in jest config:`setupFiles: ['<rootDir>/jest/setup.js', 'jest-canvas-mock'], `

I'm using lottie-web library, I've got error like this issue when run test. I've set config like above and it worked. But I've got new error: `Error: connect ECONNREFUSED 127.0.0.1:80`  :(

![Screen Shot 2020-04-29 at 10 09 21](https://user-images.githubusercontent.com/41458989/80558276-049b2480-8a04-11ea-990d-435b17148c6f.png)
![Screen Shot 2020-04-29 at 10 10 47](https://user-images.githubusercontent.com/41458989/80558287-0d8bf600-8a04-11ea-8b68-aae5e164a1f0.png)

**Comment by namlq93** [comment]
> I solved this problem is:
> 
> 1. Install`jest-canvas-mock`
> 2. Add config in jest config:`setupFiles: ['<rootDir>/jest/setup.js', 'jest-canvas-mock'], `

I'm using lottie-web library, I've got error like this issue when run test. I've set config like above and it worked. But I've got new error: `Error: connect ECONNREFUSED 127.0.0.1:80` :( 

![Screen Shot 2020-04-29 at 10 09 21](https://user-images.githubusercontent.com/41458989/80561949-5c3f8d00-8a10-11ea-89af-04ed6f85653c.png)

![Screen Shot 2020-04-29 at 10 10 47](https://user-images.githubusercontent.com/41458989/80561956-62356e00-8a10-11ea-92e5-d7d1f172bd3d.png)

**Comment by jjmerri** [comment]
The fix for me was to 
`npm install --save-dev jest-canvas-mock`
and then add this to src/setupTests.js
`import 'jest-canvas-mock';`

**Comment by EfstathiadisD** [comment]
Can I say, that this is not a solution? Why on earth, would I need another dependency? This is not acceptable I am afraid. Can someone, fix this, please. It seems that this is a problem for almost a year, and nothing is being done? Come on!!

**Comment by jtenner** [comment]
Jest canvas mock implements this function and emulates a lot of the functions properly. If perhaps importing a mock package is too much work or overhead, then don't use it?

**Comment by eli-front** [comment]
> Thanks! Turns out all I actually had to do to fix this was, well, install the canvas npm package as described in the error message!
> 
> `npm install --save-dev canvas`

Canvas is super bulk. avoid using

**Comment by EdmundMai** [comment]
For anyone who is trying to switch from react-scripts / jest to Vitest

None of the snippets I found worked, I had to modify it to dynamically import it within a function since imports are hoisted

```
import { afterAll, vi } from 'vitest';
// @ts-expect-error: Global type missing
global.jest = vi;

const apis = [
  'Path2D',
  'CanvasGradient',
  'CanvasPattern',
  'CanvasRenderingContext2D',
  'DOMMatrix',
  'ImageData',
  'TextMetrics',
  'ImageBitmap',
  'createImageBitmap',
] as const;

const createCanvasWindow = async () => {
  const getCanvasWindow = await import('jest-canvas-mock/lib/window'); //<--------- this
  return getCanvasWindow({ document: window.document });
};

const canvasWindow = createCanvasWindow;

apis.forEach((api) => {
  global[api] = canvasWindow[api];
  global.window[api] = canvasWindow[api];
});

afterAll(() => {
  // @ts-expect-error: type
  delete global.jest;
  // @ts-expect-error: type
  delete global.window.jest;
});

```

**Comment by Oleksii14** [comment]
```ts
global.HTMLCanvasElement.prototype.getContext = () => null;
global.URL.createObjectURL = () => "";
```

**Comment by wklTomorrow** [comment]
> For anyone who is trying to switch from react-scripts / jest to Vitest
> 
> None of the snippets I found worked, I had to modify it to dynamically import it within a function since imports are hoisted
> 
> ```
> import { afterAll, vi } from 'vitest';
> // @ts-expect-error: Global type missing
> global.jest = vi;
> 
> const apis = [
>   'Path2D',
>   'CanvasGradient',
>   'CanvasPattern',
>   'CanvasRenderingContext2D',
>   'DOMMatrix',
>   'ImageData',
>   'TextMetrics',
>   'ImageBitmap',
>   'createImageBitmap',
> ] as const;
> 
> const createCanvasWindow = async () => {
>   const getCanvasWindow = await import('jest-canvas-mock/lib/window'); //<--------- this
>   return getCanvasWindow({ document: window.document });
> };
> 
> const canvasWindow = createCanvasWindow;
> 
> apis.forEach((api) => {
>   global[api] = canvasWindow[api];
>   global.window[api] = canvasWindow[api];
> });
> 
> afterAll(() => {
>   // @ts-expect-error: type
>   delete global.jest;
>   // @ts-expect-error: type
>   delete global.window.jest;
> });
> ```

I tried, but it does't work, please show more

**Comment by hlawuleka** [comment]
If you are experiencing this in:

1. An Angular project
2. And in the context of an nx monorepo

The issue may be that you need to edit your specific library's `test-setup.ts` file by adding this:

```
import 'jest-preset-angular/setup-jest';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
window.HTMLCanvasElement.prototype.getContext = (): void => {
  return;
};

```

This worked for my context.
